### PR TITLE
ORION-69: Fix invalid urls of segment > 3 in length

### PR DESCRIPTION
**Pull request by markwongsk**
-- They don't redirect, but they give a better message
   now

### CODE REVIEW

**Comment by markwongsk** [comment]
@vchu123 @w10d

**Comment by vchu123** [comment]
This looks good to me.  Is dev CR okay?

**Comment by markwongsk** [comment]
I just need to fix the whitespace (my Eclipse vim settings have my >> command inserting whitespace instead of tabs).

**Comment by w10d** [comment]
the code is fine

**Pull request merged**
